# Adapted from Calin Tat's Minimal theme: https://github.com/calintat/minimal/

baseURL = "/"
languageCode = "en-us"
title = "Our Church"
# disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Peter Prescott"
    description = "The Salvation Army in Stoneycroft."
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Libre Baskerville" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
	url = "/about/"
	name = "About"
	weight = 2

[[menu.main]]
    url = "/blog/"
    name = "Blog"
    weight = 3

[[menu.main]]
    url = "/sermons/"
    name = "Sermons"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:Sam.Tomlin@salvationarmy.org.uk"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/peterprescott/stoneycroft-salvation-army"
    name = "github"
    weight = 2
